server:
  port: 81

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/api-gateway?useUnicode=true&characterEncoding=UTF-8
    # MySQL 8版本需要该class 不然会连接不上
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 一定要加s
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml